/* eslint-disable-next-line import/prefer-default-export */
export const SET_TOKEN = 'SET_TOKEN';
export const LOAD_CSV = 'LOAD_CSV';
export const SET_CSV_NAME = 'SET_CSV_NAME';
export const SET_CSV_HEADER = 'SET_CSV_HEADER';
export const SET_CSV_DATE = 'SET_CSV_DATE';
export const SET_CSV_DESCRIPTION = 'SET_CSV_DESCRIPTION';
export const SET_CSV_AMOUNT = 'SET_CSV_AMOUNT';

export const DRIVE_REQUEST_REPORTS = 'DRIVE_REQUEST_REPORTS';
export const DRIVE_GET_REPORTS_SUCCESS = 'DRIVE_GET_REPORTS_SUCCESS';
export const DRIVE_GET_REPORTS_FAILURE = 'DRIVE_GET_REPORTS_FAILURE';
export const DRIVE_NEW_SHEET_CREATED = 'DRIVE_NEW_SHEET_CREATED';

export const SHEETS_POST_CREATE = 'SHEETS_POST_CREATE';
export const SHEETS_POST_CREATE_SUCCESS = 'SHEETS_POST_CREATE_SUCCESS';
export const SHEETS_POST_CREATE_FAILURE = 'SHEETS_POST_CREATE_FAILURE';

export const SHEETS_POST_UPDATE = 'SHEETS_POST_UPDATE';
export const SHEETS_POST_UPDATE_SUCCESS = 'SHEETS_POST_UPDATE_SUCCESS';
export const SHEETS_POST_UPDATE_FAILURE = 'SHEETS_POST_UPDATE_FAILURE';

export const SHEET_CATEGORY_UPDATE_START = 'SHEET_CATEGORY_UPDATE_START';
export const SHEET_CATEGORY_UPDATE_SUCCESS = 'SHEET_CATEGORY_UPDATE_SUCCESS';
export const SHEET_CATEGORY_UPDATE_FAILURE = 'SHEET_CATEGORY_UPDATE_FAILURE';

export const SHEETS_REQUEST_PERCENTAGE = 'SHEETS_REQUEST_PERCENTAGE';
export const SHEETS_GET_PERCENTAGE_SUCCESS = 'SHEETS_GET_PERCENTAGE_SUCCESS';
export const SHEETS_GET_PERCENTAGE_FAILURE = 'SHEETS_GET_PERCENTAGE_FAILURE';

export const SPREADSHEETS_VALUES_GET_START = 'SPREADSHEETS_VALUES_GET_START';
export const SPREADSHEETS_VALUES_GET_SUCCESS = 'SPREADSHEETS_VALUES_GET_SUCCESS';
export const SPREADSHEETS_VALUES_GET_FAILURE = 'SPREADSHEETS_VALUES_GET_FAILURE';
