/* eslint-disable-next-line import/prefer-default-export */
export const SET_TOKEN = 'SET_TOKEN';
export const LOAD_CSV = 'LOAD_CSV';
export const SET_CSV_HEADER = 'SET_CSV_HEADER';

export const DRIVE_REQUEST_REPORTS = 'DRIVE_REQUEST_REPORTS';
export const DRIVE_GET_REPORTS_FAILURE = 'DRIVE_GET_REPORTS_FAILURE';
export const DRIVE_GET_REPORTS_SUCCESS = 'DRIVE_GET_REPORTS_SUCCESS';

export const SHEETS_POST_CREATE = 'SHEETS_POST_CREATE';
export const SHEETS_POST_CREATE_FAILURE = 'SHEETS_POST_CREATE_FAILURE';
export const SHEETS_POST_CREATE_SUCCESS = 'SHEETS_POST_CREATE_SUCCESS';
