# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: dev deploy

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.12.0]

    steps:
      - uses: actions/checkout@v2
      - name: Install node packages Node Version${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.0.4
        with:
          # This will be used for authentication. You can find it in your heroku homepage account settings
          heroku_api_key: ${{ secrets.HEROKU_API_KEY_NOAH }}
          # Email that you use with heroku
          heroku_email: ${{ secrets.HEROKU_EMAIL_NOAH }}
          # The appname to use for deploying/updating
          heroku_app_name: simplepnl-dev
          buildpack: mars/create-react-app
